import type { MasterProfileContent } from '../types/ats'
import { EMPTY_MASTER_PROFILE_CONTENT } from '../types/ats'
import { syncDerivedSkillLists } from './atsMatching'

/**
 * Master-Profil-Seed: Portfolio-Daten angereichert um Felder aus dem
 * hochgeladenen Master-Lebenslauf (PDF). Bestehende Levels bleiben erhalten;
 * CV ergänzt u. a. Stationen, Ausbildung, fehlende Skills und Kontaktdaten.
 * assets.cv_pdf verweist auf den echten Storage-Pfad.
 */
export function buildUserMasterProfileContent(): MasterProfileContent {
  const base: MasterProfileContent = {
    ...EMPTY_MASTER_PROFILE_CONTENT,
    personal: {
      name: 'Sven Sieber',
      email: 'designer@sven-sieber.de',
      links: {
        xing: 'https://www.xing.com/profile/Sven_Sieber',
        github: 'https://github.com/cmd-Sven',
        website: '',
        linkedin: 'https://www.linkedin.com/in/sven-sieber-860499256/',
      },
      phone: '0177 3878350',
      title: 'AI Data Analyst & Fullstack Engineer',
      location: 'Ostlandweg 16, 49205 Hasbergen',
    },
    skills: [
      {
        name: 'Supabase',
        type: 'hard',
        level: 88,
        category: 'Backend',
      },
      {
        name: 'Vercel',
        type: 'hard',
        level: 85,
        category: 'Backend',
      },
      {
        name: 'Python',
        type: 'hard',
        level: 82,
        category: 'Backend',
      },
      {
        name: 'MySQL',
        type: 'hard',
        level: 70,
        category: 'Backend',
      },
      {
        name: 'FastAPI',
        type: 'hard',
        level: 68,
        category: 'Backend',
      },
      {
        name: 'n8n',
        type: 'hard',
        level: 55,
        category: 'Backend',
      },
      {
        name: 'WordPress',
        type: 'tool',
        level: 72,
        category: 'CMS',
      },
      {
        name: 'WooCommerce',
        type: 'tool',
        level: 65,
        category: 'CMS',
      },
      {
        name: 'Shopify',
        type: 'tool',
        level: 62,
        category: 'CMS',
      },
      {
        name: 'Webflow',
        type: 'tool',
        level: 58,
        category: 'CMS',
      },
      {
        name: 'JTL 5',
        type: 'tool',
        level: 55,
        category: 'CMS',
      },
      {
        name: 'HubSpot',
        type: 'tool',
        level: 50,
        category: 'CMS',
      },
      {
        name: 'KPI-Visualisierung',
        type: 'hard',
        level: 85,
        category: 'Data/AI',
      },
      {
        name: 'Funnel-Analyse',
        type: 'hard',
        level: 82,
        category: 'Data/AI',
      },
      {
        name: 'CRO',
        type: 'hard',
        level: 80,
        category: 'Data/AI',
      },
      {
        name: 'Pandas',
        type: 'hard',
        level: 80,
        category: 'Data/AI',
      },
      {
        name: 'A/B-Testing',
        type: 'hard',
        level: 78,
        category: 'Data/AI',
      },
      {
        name: 'Claude Code',
        type: 'hard',
        level: 78,
        category: 'Data/AI',
      },
      {
        name: 'SQL',
        type: 'hard',
        level: 78,
        category: 'Data/AI',
      },
      {
        name: 'Tableau / PowerBI',
        type: 'hard',
        level: 75,
        category: 'Data/AI',
      },
      {
        name: 'Matplotlib',
        type: 'hard',
        level: 72,
        category: 'Data/AI',
      },
      {
        name: 'Streamlit',
        type: 'tool',
        level: 70,
        category: 'Data/AI',
      },
      {
        name: 'NumPy / SciPy',
        type: 'hard',
        level: 68,
        category: 'Data/AI',
      },
      {
        name: 'Docker',
        type: 'hard',
        level: 65,
        category: 'Data/AI',
      },
      {
        name: 'LangChain',
        type: 'hard',
        level: 62,
        category: 'Data/AI',
      },
      {
        name: 'Web3 / Three.js',
        type: 'hard',
        level: 60,
        category: 'Data/AI',
      },
      {
        name: 'AG2',
        type: 'hard',
        level: 58,
        category: 'Data/AI',
      },
      {
        name: 'Hugging Face',
        type: 'hard',
        level: 55,
        category: 'Data/AI',
      },
      {
        name: 'Runway',
        type: 'hard',
        level: 55,
        category: 'Data/AI',
      },
      {
        name: 'Figma',
        type: 'tool',
        level: 90,
        category: 'Design',
      },
      {
        name: 'Accessibility',
        type: 'hard',
        level: 78,
        category: 'Design',
      },
      {
        name: 'Photoshop',
        type: 'tool',
        level: 78,
        category: 'Design',
      },
      {
        name: 'Illustrator',
        type: 'tool',
        level: 75,
        category: 'Design',
      },
      {
        name: 'Design Tokens',
        type: 'hard',
        level: 72,
        category: 'Design',
      },
      {
        name: 'Canva',
        type: 'tool',
        level: 70,
        category: 'Design',
      },
      {
        name: 'Adobe XD',
        type: 'tool',
        level: 60,
        category: 'Design',
      },
      {
        name: 'Sketch',
        type: 'tool',
        level: 55,
        category: 'Design',
      },
      {
        name: 'React',
        type: 'hard',
        level: 92,
        category: 'Frontend',
      },
      {
        name: 'TypeScript',
        type: 'hard',
        level: 80,
        category: 'Frontend',
      },
      {
        name: 'Tailwind CSS',
        type: 'hard',
        level: 88,
        category: 'Frontend',
      },
      {
        name: 'Cursor',
        type: 'hard',
        level: 85,
        category: 'Frontend',
      },
      {
        name: 'Next.js',
        type: 'hard',
        level: 82,
        category: 'Frontend',
      },
      {
        name: 'SVG',
        type: 'hard',
        level: 80,
        category: 'Frontend',
      },
      {
        name: 'Vue',
        type: 'hard',
        level: 78,
        category: 'Frontend',
      },
      {
        name: 'daisyUI',
        type: 'hard',
        level: 75,
        category: 'Frontend',
      },
      {
        name: 'Three.js',
        type: 'tool',
        level: 62,
        category: 'Frontend',
      },
      {
        name: 'T-Shaped Thinking',
        type: 'soft',
        level: 90,
        category: 'Soft Skills',
      },
      {
        name: 'Strukturiertes Problemlösen',
        type: 'soft',
        level: 88,
        category: 'Soft Skills',
      },
      {
        name: 'Stakeholder-Kommunikation',
        type: 'soft',
        level: 85,
        category: 'Soft Skills',
      },
      {
        name: 'Cross-functional Collaboration',
        type: 'soft',
        level: 82,
        category: 'Soft Skills',
      },
      {
        name: 'User Research & Iteration',
        type: 'soft',
        level: 80,
        category: 'Soft Skills',
      },
      {
        name: 'Visuelles Storytelling',
        type: 'soft',
        level: 78,
        category: 'Soft Skills',
      },
      {
        name: 'Express.js',
        category: 'Backend',
        level: 80,
        type: 'hard',
      },
      {
        name: 'MongoDB',
        category: 'Backend',
        level: 75,
        type: 'hard',
      },
      {
        name: 'RESTful APIs & Webhooks',
        category: 'Backend',
        level: 85,
        type: 'hard',
      },
      {
        name: 'NeuroFlash',
        category: 'CMS',
        level: 60,
        type: 'tool',
      },
      {
        name: 'SEO (Systrix, SERanking)',
        category: 'CMS',
        level: 80,
        type: 'hard',
      },
      {
        name: 'Predictive Analytics',
        category: 'Data/AI',
        level: 75,
        type: 'hard',
      },
      {
        name: 'Prompt Engineering',
        category: 'Data/AI',
        level: 90,
        type: 'tool',
      },
      {
        name: 'Machine Learning & AI',
        category: 'Data/AI',
        level: 78,
        type: 'hard',
      },
      {
        name: 'VUI/UX Design & Analytics',
        category: 'Design',
        level: 85,
        type: 'hard',
      },
      {
        name: 'Adobe Creative Cloud',
        category: 'Design',
        level: 85,
        type: 'tool',
      },
      {
        name: 'Agile Entwicklung (Scrum)',
        category: 'Soft Skills',
        level: 85,
        type: 'soft',
      },
      {
        name: 'Design Thinking',
        category: 'Soft Skills',
        level: 85,
        type: 'soft',
      },
      {
        name: 'Six Sigma Yellow Belt',
        category: 'Qualität',
        level: 80,
        type: 'hard',
      },
      {
        name: 'Amazon Leadership Principles',
        category: 'Qualität',
        level: 90,
        type: 'soft',
      },
      {
        name: 'JavaScript (ES6+)',
        category: 'Frontend',
        level: 90,
        type: 'hard',
      },
      {
        name: 'HTML5 / CSS3',
        category: 'Frontend',
        level: 92,
        type: 'hard',
      },
      {
        name: 'Node.js',
        category: 'Backend',
        level: 85,
        type: 'hard',
      },
      {
        name: 'Git-Versionsverwaltung',
        category: 'Soft Skills',
        level: 85,
        type: 'tool',
      },
    ],
    projects: [
      {
        url: 'https://goexplore-app.vercel.app',
        name: 'GOEXPLORE',
        tech: [
          'Data Analytics',
          'TypeScript',
          'KPI-Visualisierung',
          'Szenario-Analyse',
        ],
        description: 'CEO-Dashboard für Wachstumsentscheidungen — Ich habe Verkaufsdaten so aufbereitet, dass Expansion und Preis-Szenarien interaktiv vergleichbar werden – kein statischer Report, sondern ein Briefing-Cockpit.',
        portfolio_id: 'goexplore',
      },
      {
        url: 'https://table-heroes.de',
        name: 'TABLE HEROES',
        tech: [
          'Next.js',
          'Supabase',
          'React',
          'Three.js',
        ],
        description: 'TTRPG-Community & Kampagnen-Plattform — Mein einziges laufendes Produkt: Community, Lore/Kampagnen und Session-Board unter table-heroes.de – produktiv betrieben, nicht nur als Demo.',
        portfolio_id: 'tableheroes',
      },
      {
        url: 'https://python-lernplattform.vercel.app',
        name: 'PCEP LERNPLATTFORM',
        tech: [
          'UI/UX',
          'Next.js',
          'DaisyUI',
          'Supabase',
        ],
        description: 'Lernfluss, Onboarding & Feedback-Schleife — Ich habe die PCEP-Vorbereitung um ein klares Onboarding und Übungsfluss herum gestaltet – und anhand von Teilnehmer-Feedback iteriert.',
        portfolio_id: 'lernplattform',
      },
      {
        url: 'https://github.com/cmd-Sven/bookworm-app',
        name: 'BOOKWORM',
        tech: [
          'Next.js',
          'Supabase',
          'Python / Streamlit',
          'Auth & RLS',
        ],
        description: 'Bücherverleih unter Freunden — Ich habe den Ausleihprozess digitalisiert: Katalog, Fristen, Auth – Next.js als Hauptapp, Streamlit als schneller Prototyp auf derselben Supabase-DB.',
        portfolio_id: 'bookworm',
      },
      {
        name: 'Fullstack Development & AI Research',
        description: 'Seit 2026: Eigenständige Projekte — AI & Web Integration: Entwicklung und Testing KI-gestützter Prototypen und Automations-Schnittstellen (n8n). Hands-on Practice: Vertiefung moderner Frameworks, Prompt-Engineering-Workflows und Datenanalysen.',
        tech: [
          'React',
          'Node.js',
          'n8n',
          'LLM APIs',
          'Python',
          'Prompt Engineering',
        ],
        url: 'https://sven-sieber.de',
      },
    ],
    stations: [
      {
        company: 'MadeByMates GmbH & Co. KG, Hagen',
        role: 'Full-Stack & Systems Architect',
        from: '08/2022',
        to: '02/2025',
        highlights: [
          'System-Architektur: Technische Planung und Full-Stack-Umsetzung der Plattform FulfilledByMates.com',
          'E-Commerce & APIs: Anbindung von JTL Shop 5 an die WaWi inklusive Prozessautomatisierung via Schnittstellen',
          'Automation: Entwicklung automatisierter User Journeys und technisches Setup von HubSpot-Workflows',
          'Technical Consulting: Technisches Onboarding und Schnittstellen-Support für Key-Accounts (u. a. HABA Group)',
        ],
      },
      {
        company: 'Autohaus SIEMON GmbH, Ibbenbüren',
        role: 'Web- & Logic-Engineer',
        from: '11/2021',
        to: '07/2022',
        highlights: [
          'Web-Infrastruktur: Neuentwicklung und technische Skalierung der Webpräsenzen für mehrere Standorte',
          'Logic-Engineering: Entwicklung eines interaktiven Auto- & Servicekonfigurators zur Prozessautomatisierung',
          'Conversion-Optimierung: Aufbau von SEO-Strategien, E-Mail-Workflows und Performance-Landingpages',
          'Social Systems: Strategische Optimierung und technische Pflege der Social-Media-Schnittstellen',
        ],
      },
      {
        company: 'Westfalen AG, Münster',
        role: 'Project Manager / Frontend Developer',
        from: '03/2021',
        to: '03/2022',
        highlights: [
          'Enterprise Design Systems: Sicherstellung der CI-Konformität und technische Weiterentwicklung der Konzern-Webpräsenz',
          'Stakeholder-Management: Projektkoordination und Abstimmung in komplexen Konzernstrukturen über verschiedene Fachabteilungen hinweg',
          'CI-Transformation: Projektleitung beim technischen und visuellen Redesign der digitalen Plattformen basierend auf der neuen Corporate Identity',
        ],
      },
      {
        company: 'Yupet Marktplaner GmbH, Dinklage',
        role: 'Mediengestalter Print & Web',
        from: '11/2017',
        to: '02/2021',
        highlights: [
          'Editorial Design: Eigenverantwortliches Layout, Satz und Bildbearbeitung für monatliche Fachzeitschrift und Branchenkataloge',
          'Druckvorstufe: Erstellung fehlerfreier Druckdaten (Reinzeichnung) und Kommunikation mit Druckereien',
          'Bildmanagement: Strukturierte Pflege und Bearbeitung umfangreicher Bilddatenbanken für Print und Web',
        ],
      },
      {
        company: 'Amazon Fulfillment Germany GmbH, Rheinberg',
        role: 'Prozess- & Schnittstellen-Manager',
        from: '09/2012',
        to: '09/2017',
        highlights: [
          'Prozess-Optimierung: Analyse und Verbesserung interner Abläufe (Logistik) – Verständnis für Warenwirtschaft und Supply Chain',
          'Visualisierung: Erstellung von Hallenplänen, Schulungsunterlagen und Prozess-Grafiken',
          'Schnittstellen: Technische Beratung von Großkunden zur EDV-Anbindung',
          'Planung und Weiterentwicklung des License Plate Prozesses in DUS2',
        ],
      },
    ],
    education: [
      {
        institution: 'WBS CODING SCHOOL, Berlin',
        degree: 'Data Analyst AI',
        from: '04/2026',
        to: '01/2027',
        notes: 'Statistische Datenanalyse, Datenbereinigung und Data Wrangling mit Python (Pandas, NumPy). Machine Learning & AI: Entwicklung und Anwendungsbereiche von ML-Modellen zur Mustererkennung sowie KI-Integration. SQL & Visualisierung: Abfrage komplexer relationaler Datenbanken und Erstellung interaktiver Dashboards.',
      },
      {
        institution: 'WBS CODING SCHOOL, Berlin',
        degree: 'Web & App Fullstack Development',
        from: '04/2026',
        to: '01/2027',
        notes: 'Frontend & Logic: React (inkl. TypeScript), JavaScript (ES6+), HTML5 und CSS3/Tailwind. Backend & Cloud: Node.js/Express; Datenmodellierung in MongoDB und Supabase (SQL). AI-Native Development: AI-Workflows (Vibecoding) mit Cursor, Claude und LLM-Integrationen. Agile Praxis: Scrum und Git-Versionsverwaltung.',
      },
      {
        institution: 'Papierprint IT GmbH, Konstanz',
        degree: 'Mediengestalter Digital und Print',
        from: '2009',
        to: '2011',
        notes: 'Medienproduktion: Schwerpunkt Digitales Design und Crossmedia-Konzeption. Web-Development: Erstellung, technische Pflege und Content-Management von Webpräsenzen. Digital Marketing: Umsetzung technischer Marketingmaßnahmen und digitaler Werbemittel.',
      },
    ],
    languages: [
      {
        name: 'Deutsch',
        level: 'Muttersprache',
      },
      {
        name: 'Englisch',
        level: 'C1',
      },
    ],
    interests: [
      'Datengetriebene Produktentscheidungen',
      'TTRPG / Community-Produkte',
      'Design Systems',
      'Agentic AI',
      'Prompt Engineering',
      'Prozessoptimierung',
      'KI-Prototyping',
    ],
    blog_topics: [
      'Accessibility',
      'Architektur',
      'CRO',
      'Datenanalyse',
      'Design Systems',
      'Figma',
      'Performance',
      'React',
      'SVG',
      'Tailwind',
      'UX',
      'Vue',
      'Prompt Engineering',
      'Machine Learning',
      'Automation',
      'HubSpot Workflows',
    ],
    wording: {
      tone: 'Klar, konkret, ohne Buzzwords. Erste Person Singular wo sinnvoll. Fokus auf Transfer und messbaren Impact.',
      summary: 'Ich verknüpfe tiefgreifendes UX/UI-Verständnis und moderne Full-Stack-Entwicklung mit fortgeschrittener KI-Datenanalyse. Von der visuellen Ästhetik über die technische Software-Architektur bis hin zur datenbasierten Optimierung baue ich digitale Ökosysteme, die nicht nur gut aussehen, sondern performen.\n\nIch verbinde Mediengestaltung, UX/UI und Full-Stack-Entwicklung mit einem wachsenden Datenanalyse-Fokus. Mein Ziel: digitale Produkte, die nicht nur gut aussehen, sondern messbar performen.\n\nIn Projekten arbeite ich strukturiert von der Hypothese über Prototyp bis zur Auswertung – ob Conversion-Optimierung, Dashboard oder interoperable Frontends mit React und Vue.\n\nAktuell schließe ich meine Spezialisierung zum Datenanalysten ab und suche ein Umfeld, in dem Design, Technik und Business Intelligence zusammenwirken.',
      keywords: [
        'T-Shaped: breite UX/UI & Dev, tiefe Datenkompetenz',
        'React, Vue, TypeScript, Tailwind, SVG-Visualisierung',
        'CRO, Funnel-Analyse, A/B-Tests & KPI-Denken',
        'Product Design',
        'Analytics',
        'Prototyping',
        'Full-Stack',
        'Conversion-Optimierung',
        'Prompt Engineering',
        'Node.js',
        'Express.js',
        'MongoDB',
        'Six Sigma',
        'Scrum',
        'n8n',
        'HubSpot',
      ],
      hero_badge: 'Spezialisierung Datenanalyse im Endspurt – Bereit für neue Herausforderungen',
      hero_subline: 'Hi, ich bin Sven. Ich verbinde',
      hero_headline: 'Design, Code und Daten zu messbarem Erfolg.',
    },
    assets: {
      photo: null,
      cv_pdf: '938b17e3-41b2-4860-808a-4b583087ec6c/cv.pdf',
      signature: null,
    },
  }

  return syncDerivedSkillLists(base)
}
